!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Context


Person(Visitor, "Клиент [Пользователь]", "Использование скидок, использование акций, использование бонусных баллов")
Person(Manager, "Мэнеджер [Пользователь]", "Создание скидок\акций, редактирование скидок\акций, аналитика скидок\акций")
Person(Admin, "Админ [Пользователь]", "Использование скидок, использование бонусных баллов")


System(App, "Система управления лояльностью клиентов [Программная система]", "Система для разработки и управления акционными и скидочными программами а также бонусных систем с целью увеличения уровня лояльности клиентов")

System_Ext(EMAIL, "Почтовая система [Программная система]", "Поставщик системы отправки электронных писем")
System_Ext(Payment, "Система оплаты [Программная система]", "Приём платежей, интернет эквайринг")
System_Ext(FNS, "ФНС API [Программная система]", "Автоматизация извлечения данных из Единого государственного реестра юридических лиц (ЕГРЮЛ) и Единого государственного реестра индивидуальных предпринимателей (ЕГРИП)")
System_Ext(Company, "Система компании [Программная система]", "Набор инструментов, который использует компания")
System_Ext(GoogleAnalitycs, "Google analitycs [Программная система]", "Набор инструментов для аналитики безнеспроцессов")



Rel(Visitor, App, "Получение скидок, акций, участие в бонусных программах")
Rel(Manager, App, "Проектирование и редактирование скидочных, бонусных и акционных программ. Проведение анализа")
Rel(Admin, App, "Управление и редактирование над другими администраторами и менеджерами. Управление и редактирование скидочных, акционных и бонусных программ")

Rel(App, EMAIL, "Отправка электронных писем")
Rel(App, Payment, "Оплата")
Rel(App, FNS, "Проверка компаний")
Rel(App, Company, "Интеграция данных")
Rel(App, GoogleAnalitycs, "Проведение аналитики через сторонние сервисы")