@startuml
|Клиент|
start
:Выбрать товар;
:Начать оформление покупки;
|Сервис скидок|
:Создать корзину;

|Клиент|
while (Клиент хочет перейти к оплате?) is(Нет)
    if (Клиент хочет удалить товар из корзины?) then(да)
        :Удалить товар из корзины;
        
    else(нет)
        |Клиент|
        :Найти товар;
        :Добавить товар в корзину;
    endif
    |Сервис скидок|
    :Посчитать общую цену;
    :Посчитать бонусные баллы;
    :Применить акции;
endwhile(Да)
|Клиент|


if (клиент согласился оплатить?) then (да)
    
    |Сервис скидок|
    while (Клиент предоставил нужную денежную сумму?) is(нет)
        if (время ожидания подошло к пределу?) then (да)
            :Отменить покупку;
            stop
        endif
        |Клиент|

        :Выбор способа оплаты;
    endwhile(да)
    |Сервис скидок|
    :Провести плату;
    if (Клиент применил бонусную карту) then (да)
        :Начислить бонусные баллы;
    endif

    if (Клиент согласился получить копию чека?) then (да) 
        :Отправить чек;
    endif
    
    stop
else (нет) 
|Сервис скидок|
:Отменить покупку;
stop
@enduml